package lexer;

public enum TokenType {
    identifier,
    literal_Integers,
    assignment_operator,
    open_parenthesis,
    close_parenthesis,
    IF_keyword,
    THEN_keyword,
    ELSE_keyword,
    WHILE_keyword,
    PRINT_keyword,
    REPEAT_keyword,
    UNTIL_keyword,
    DO_keyword,
    le_operator,
    lt_operator,
    ge_operator,
    gt_operator,
    eq_operator,
    ne_operator,
    add_operator,
    sub_operator,
    mult_operator,
    div_operator,
    addEq_operator,
    END,
    FUNCTION
}